### ISSUE TITLE
Incorrect flash message displayed upon logging out

### ISSUE THREAD

**Issue by Eduardo06sp** [egemen-github/odinbar#2]
Upon logging out, a flash message at the top reads: `You need to sign in or sign up before continuing.`

To reproduce, simply log in, then log out.
Tested in Linux Firefox (Developer) v103.

**Comment by egemen-dev** [comment]
I think flash message is not incorrect as it is pretty logical to see it after you got redirected to sign in page.

**Comment by egemen-dev** [comment]
Thank you @Eduardo06sp for the feedback 👍 

I'm closing this issue. Feel free to open new one if you find any in the future.
