### ISSUE TITLE
bug: Clicking "Cancel my account" causes error.

### ISSUE THREAD

**Issue by crespire** [egemen-github/odinbar#3]
On the user end, nothing seems to happen, but the console logs an error: https://i.vgy.me/5iYCqN.gif

I am also not able to log in again with the same information, so the user does seem to get deleted in the back end.

**Comment by egemen-dev** [comment]
Hi @crespire, thank you for letting me know about this issue. I think I fixed the issue by overwriting the devise controller. Please confirm that it works :)

**Comment by crespire** [comment]
Yep, everything seems to be working now!
